# Conexi贸n con la base de datos principal
database:
  host: localhost
  user: root
  pass: 
  name: ocrend
  port: 1521
  protocol: TCP
  motor: mysql
  
# Configuraci贸n de servidor SMTP
phpmailer:
  host: 
  user:
  pass:
  port: 465

# Credenciales de uso de SDK PayPal
paypal:
  mode: sandbox
  client_id: 
  client_secret:

# Configuraci贸n de sesiones
sessions:
  life_time: 3600 

# Variables del framework
framework:
  firewall: true
  debug: true
  version: 2.0.0

# Configuraci贸n del sitio
site:
  name: Ocrend Framework 2
  author: Ocrend Software
  url: http://localhost/Framework/
